groupIds = [ 6162 ]
excludeSubjects = [ "Военная подготовка" ]
requestForWeeks = 0
appAccess = "Basic"
accessToken = "..."
refreshToken = "..."
username = "...@dvfu.ru"
password = "..."

[calendarByGroups]
  3 = ""
  default = "https://caldav/calendar"
